---
- name: Create adguardhome directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/adguardhome"
    - "{{ docker_base_dir }}/adguardhome/work"
    - "{{ docker_base_dir }}/adguardhome/conf"

- block:
    - name: Create adguardhome docker compose file
      ansible.builtin.template:
        src: adguardhome/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/adguardhome/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create adguardhome systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@adguardhome.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart adguardhome
