---
- name: Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}"
  tags:
    - always

# Manage Docker installation
- import_tasks: docker.yml

# Manage applications
- import_tasks: node-exporter.yml
- import_tasks: homeassistant.yml
- import_tasks: adguard.yml
- import_tasks: homebridge.yml
- import_tasks: zigbee2mqtt.yml
