---
- name: pull scrypted
  docker_image:
    name: ghcr.io/koush/scrypted
    tag: 18-jammy-full-v0.39.1
    source: pull

- name: Create scrypted directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/scrypted"
    - "/storage/scrypted"

- block:
    - name: Create scrypted docker compose file
      ansible.builtin.template:
        src: scrypted/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/scrypted/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create scrypted systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@scrypted.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart scrypted
