---
- name: Create zigbee2mqtt directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: users
    mode: 0775
  loop:
    - "{{ docker_base_dir }}/zigbee2mqtt"
    - "{{ docker_base_dir }}/zigbee2mqtt/data"

- block:
    - name: Create zigbee2mqtt docker compose file
      ansible.builtin.template:
        src: zigbee2mqtt/docker-compose.yml.j2
        dest: "{{ docker_base_dir }}/zigbee2mqtt/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create zigbee2mqtt config file
      ansible.builtin.template:
        src: zigbee2mqtt/configuration.yaml.j2
        dest: "{{ docker_base_dir }}/zigbee2mqtt/data/configuration.yaml"
        owner: "{{ ansible_user }}"
        group: users
        mode: 0775
    - name: Create zigbee2mqtt systemd service file
      ansible.builtin.template:
        src: "docker-compose@.service.j2"
        dest: "/etc/systemd/system/docker-compose@zigbee2mqtt.service"
        mode: 0644
      vars:
        condition_path_is_mount_point: "/"
  notify: Restart zigbee2mqtt
