---
- name: Restart docker-cleanup
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - docker-cleanup.service
    - docker-cleanup.timer

- name: Restart node-exporter
  ansible.builtin.systemd:
    name: "docker-compose@node-exporter.service"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart homeassistant
  ansible.builtin.systemd:
    name: "docker-compose@homeassistant.service"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart adguardhome
  ansible.builtin.systemd:
    name: "docker-compose@adguardhome.service"
    state: restarted
    enabled: true
    daemon_reload: true