---
- name: Install filesystem tools
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - nfs-common
    - nfs-kernel-server
    - samba
    - socat

- name: Disable swap at runtime
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap on boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
